# Site settings
short_title: Orcas
title: Orcas - Automatic deployment for the database
description: >
 Orcas is an Open Source Deployment framework for transferring an existing database schema into a target state defined by Orcas. Orcas stands for Oracle adaptive schemas” and is only compatible with Oracle RDBMS.

# Twitter
twitter:
  username: OC_WIRE

# GitHub (required for local site builds)
github:
  owner_name: opitzconsulting
  repository_name: orcas
  repository_url: https://github.com/opitzconsulting/orcas

# Build settings
baseurl:
plantumlbaseurl: http://www.plantuml.com/plantuml/proxy?cache=no&src=https://raw.github.com/opitzconsulting/orcas/gh-pages/_docs/plantuml
permalink: docs/:title
markdown: kramdown
highlighter: rouge
relative_permalinks: false
collections:
  docs:
    output: true
